export PS1='\u@\h \w '

# Just in case, when we're sharing stuff... 
#umask 0
# Group ngi-sw MUST have rw or else all hell breaks loose! 
umask 0002

# We need a writeable place when running Ansible for tmp files
export HOME=/tmp/ngi-sw-`whoami`
#export HOME=/tmp/ngi-sw-home/
mkdir -p $HOME 

# Bootstrap a log directory 
mkdir -p /lupus/ngi/irma3/log

# We need the Ansible env for running ansible commands 
alias ansibleenv='source /lupus/ngi/irma3/ansible-env/bin/activate'

# We're using Anaconda when setting up the NGI pipeline environment. 
# Perhaps not necessary. 
export PATH="/lupus/ngi/sw/anaconda/bin:$PATH"
alias ngienv='source activate NGI'

# Force the user to have ngi-sw as gid (inherits the parent environment)
# This needs to be the last thing to run 
newgrp ngi-sw 
