#export PS1='\u@\h \w '

# Group ngi-sw MUST have rw or else all hell breaks loose! 
umask 0002

# These days irma3 mounts home dirs from pica instead. 
# We need a writeable place when running Ansible for tmp files
#export HOME=/tmp/ngi-sw-`whoami`
#export HOME=/tmp/ngi-sw-home/
#mkdir -p $HOME 

# Bootstrap a log directory 
mkdir -p /lupus/ngi/irma3/log

# We need the Ansible env for running ansible commands 
# Note though that this alias will not work at the moment
# due to the required newgrp command below. 
#alias ansibleenv='source /lupus/ngi/irma3/ansible-env/bin/activate'

# We're using Anaconda when setting up the NGI pipeline environment. 
# Perhaps not necessary. 
#export PATH="/lupus/ngi/sw/anaconda/bin:$PATH"
#alias ngienv='source activate NGI'

# Force the user to have ngi-sw as gid (inherits the parent environment)
# This needs to be the last thing to run 
newgrp ngi-sw 
