--- 

- name: create qualimap destination directory 
  file: path={{ qualimap_dest }} state=directory mode=g+rwxs
  tags: ngi_piper  

- name: download qualimap archive
  get_url:
    url: "{{ qualimap_url }}"
    dest: "{{ qualimap_dest }}/{{ qualimap_file }}"
    mode: g+rw
  tags: ngi_piper

- name: unpack qualimap to destination
  unarchive: 
    src: "{{ qualimap_dest }}/{{ qualimap_file }}" 
    dest: "{{ qualimap_dest }}/" 
    copy: no 
    creates: "{{ qualimap_path }}/LICENSE"
    mode: g+rw
  tags: ngi_piper

# FIXME: Not bundled in new version of Piper. 
# Only needed for RNA-seq though
#- name: copy FixEmptyReads.pl from piper src to destination 
#  copy:
#    src: "{{ sync_cutadapt_src }}"
#    remote_src: yes
#    dest: "{{ sync_cutadapt_dest }}"
#    mode: g+rw 
#  tags: ngi_piper

- name: download rna-seqc jar file
  get_url: 
    url: "{{ rna_seqc_url }}"
    dest: "{{ rna_seqc_dest }}"
    mode: g+rw
  tags: ngi_piper

